function [fig,ax, hb] = Pl_LinCompPlot(SS_desc_f1, SS_desc_f2, contmat_E1, contmat_E2)


% Channels to be plotted if available
DOFs =  {0,         'Platform horizontal surge translation, m'                    ;...
         0,         'Platform horizontal sway translation, m'                     ;...
         0,         'Platform vertical heave translation, m'                      ;...
         0,         'Platform roll tilt rotation, deg'                            ;...
         1,         'Platform pitch tilt rotation, deg'                           ;...
         0,         'Platform yaw rotation, deg'                                  ;...
         1,         '1st tower fore-aft bending mode, m'                          ;...
         1,         '1st tower side-to-side bending mode, m'                      ;...
         0,         '2nd tower fore-aft bending mode, m'                          ;...
         0,         '2nd tower side-to-side bending mode, m'                      ;...
         1,         'Nacelle yaw, deg'                                            ;...
         0,         'Variable speed generator, deg'                               ;...
         1,         'Drivetraiden rotational-flexibility, deg'                      ;...
         0,         '1st flapwise bending-mode of coning mode, m'                 ;...
         0,         '1st flapwise bending-mode of cosine-cyclic mode, m'          ;...
         0,         '1st flapwise bending-mode of sine-cyclic mode, m'            ;...
         0,         '1st edgewise bending-mode of coning mode, m'                 ;...
         0,         '1st edgewise bending-mode of cosine-cyclic mode, m'          ;...
         0,         '1st edgewise bending-mode of sine-cyclic mode, m'            ;...
         0,         '2nd flapwise bending-mode of coning mode, m'                 ;...
         0,         '2nd flapwise bending-mode of cosine-cyclic mode, m'          ;...
         0,         '2nd flapwise bending-mode of sine-cyclic mode, m'            ;...
         % As it is currently, the derivative terms will always be plotted
         0,         'd/dt of Platform horizontal surge translation, m/s'          ;...
         0,         'd/dt of Platform horizontal sway translation, m/s'           ;...
         0,         'd/dt of Platform vertical heave translation, m/s'            ;...
         0,         'd/dt of Platform roll tilt rotation, deg/s'                  ;...
         0,         'd/dt of Platform pitch tilt rotation, deg/s'                 ;...
         0,         'd/dt of Platform yaw rotation, deg/s'                        ;...
         0,         'd/dt of 1st tower fore-aft bending mode, m/s'                ;...
         0,         'd/dt of 1st tower side-to-side bending mode, m/s'            ;...
         0,         'd/dt of 2nd tower fore-aft bending mode, m/s'                ;...
         0,         'd/dt of 2nd tower side-to-side bending mode, m/s'            ;...
         0,         'd/dt of Nacelle yaw, deg/s'                                  ;...
         0,         'd/dt of Variable speed generator, deg/s'                     ;...
         0,         'd/dt of Drivetrain rotational-flexibility, deg/s'            ;...
         0,         'd/dt of 1st flapwise bending-mode of coning mode, m/s'       ;...
         0,         'd/dt of 1st flapwise bending-mode of cosine-cyclic mode, m/s';...
         0,         'd/dt of 1st flapwise bending-mode of sine-cyclic mode, m/s'  ;...
         0,         'd/dt of 1st edgewise bending-mode of coning mode, m/s'       ;...
         0,         'd/dt of 1st edgewise bending-mode of cosine-cyclic mode, m/s';...
         0,         'd/dt of 1st edgewise bending-mode of sine-cyclic mode, m/s'  ;...
         0,         'd/dt of 2nd flapwise bending-mode of coning mode, m/s'       ;...
         0,         'd/dt of 2nd flapwise bending-mode of cosine-cyclic mode, m/s';...
         0,         'd/dt of 2nd flapwise bending-mode of sine-cyclic mode, m/s'  };
     
% Some variable definitions and housekeeping
Evec1 = contmat_E1(:,end);
Evec2 = contmat_E2(:,end);
DOF_str = DOFs(:,2);
 
% Define desired states to be plotted
pl_st1 = zeros(length(SS_desc_f1),1);
pl_st2 = zeros(length(SS_desc_f2),1);
for dind = 1:length(DOFs)
    if DOFs{dind,1}
            pl_st1 = pl_st1 + contains(SS_desc_f1,DOFs{dind,2});
            pl_st2 = pl_st2 + contains(SS_desc_f2,DOFs{dind,2});
    end
end

if sum(pl_st1>0) ~= sum(pl_st2>0)
    error('You''re trying to plot degrees of freedom that don''t exist in both control energy matrices - oops.')
end
% Make plot vectors
Evec1_pl = Evec1(pl_st1>0);
Evec2_pl = Evec2(pl_st2>0);
SS_desc_f_pl = SS_desc_f1(pl_st1>0);

%plot and format
hb = barh(flipud((Evec2_pl - Evec1_pl)./Evec1_pl),'stacked');
ax = gca;
fig = gcf;
% 
% ax.YTick = 1:length(SS_desc_f_pl);
ax.YTickLabel = [];flipud(SS_desc_f_pl);

% figure
% bar([Evec1_pl Evec2_pl])
%% Plot formatting
ax.FontSize = 18;
ax.TitleFontSizeMultiplier = 1.11;
% title('Control Energy Comparison')
title('Control Direction Comparison')
% xlabel('Normalized Relative Control Energy')
xlabel('Normalized Relative Control Direction')
% fig.PaperPosition = [0 0 6.5 1.8];


% %% windtech formatting
% ax.FontSize = 9;
% ax.TitleFontSizeMultiplier = 1.11;
% ax.FontName = 'times';
% title('Control Energy Comparison')
% % xlabel('Normalized Relative Control Energy, \big($((kNm)^2 + deg^2)s$\big)','interpreter','latex')
% xlabel('Normalized Relative Control Energy')
% fig.PaperPosition = [0 0 6.5 1.8];
